# Generated by Django 4.2.5 on 2023-11-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('codAyuda', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAyuda', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idMedicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('presentacion', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField()),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalClinica',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=3)),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('codProcedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProcedimiento', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitaEnfermera',
            fields=[
                ('idVisita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('presionArterial', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('pulso', models.CharField(max_length=10)),
                ('nivelOxigeno', models.FloatField()),
                ('observaciones', models.CharField(max_length=250, null=True)),
                ('recordatorioSiguienteVisia', models.CharField(max_length=30, null=True)),
                ('cedulaPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
                ('idOrden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.orden')),
                ('usuarioEnfermera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='SeguroPaciente',
            fields=[
                ('idSeguro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreAseguradora', models.CharField(max_length=30)),
                ('vigencia', models.DateField()),
                ('estado', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProcedimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(null=True)),
                ('asistenciaEspecializada', models.CharField(max_length=30)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.orden')),
                ('idProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('dosis', models.CharField(max_length=30)),
                ('tiempoTratamiento', models.IntegerField(default=0)),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medicamento')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenAyudaDiagnostica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(null=True)),
                ('asistenciaEspecializada', models.CharField(max_length=30)),
                ('revision', models.BooleanField(default=False)),
                ('idAyuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.ayuda')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cedulaMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cedulaPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente'),
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('idNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('tiempo', models.IntegerField()),
                ('fechaRegistro', models.DateField()),
                ('observaciones', models.CharField(max_length=250)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='informaContacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('relacion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('copago', models.FloatField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.seguropaciente')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.personalclinica')),
            ],
        ),
    ]
