# Generated by Django 4.2.5 on 2023-11-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalclinica',
            name='cedula',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
