# Generated by Django 4.2.5 on 2023-11-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_alter_personalclinica_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalclinica',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
